language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  - ./travis.sh

env:
  global:
    - DISPLAY=:99.0
    - JENKINS_VERSION=1.580.3
  matrix:
    - TARGET=CI

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar

notifications:
  email: false
  webhooks:
    - secure: "JWhfaDTuY/3mpOwGzfBFHO9Y3nEz98FVWrn9yuTPRqRVCFUXdO7G63QWwQiyr7VQoq2IrbsRpbX7ssWW3dJN8sdVwQarRgsVq30KzPONI77/U0Lw9OmixukBnt2IEgjGiJrmBUARd5naCejGlA7iNCLfFbEoudnSMhsdBHux82Y=" 
